# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `console_table` gem.
# Please instead update this file by running `bin/tapioca gem console_table`.


# source://console_table//lib/console_table.rb#7
module ConsoleTable
  class << self
    # Define a console table.  Requires a table layout which specifies column information
    # like sizes, titles, and key names.
    #
    # source://console_table//lib/console_table.rb#11
    def define(layout, options = T.unsafe(nil), &block); end
  end
end

# source://console_table//lib/console_table.rb#18
class ConsoleTable::ConsoleTableClass
  # @return [ConsoleTableClass] a new instance of ConsoleTableClass
  #
  # source://console_table//lib/console_table.rb#31
  def initialize(column_layout, options = T.unsafe(nil)); end

  # Add rows to the table.  Prints immediately, consult documentation for examples
  #
  # source://console_table//lib/console_table.rb#25
  def <<(options); end

  # Add strings to the footer array to have them formatted when the table closes
  #
  # source://console_table//lib/console_table.rb#22
  def footer; end

  protected

  # source://console_table//lib/console_table.rb#107
  def print_footer; end

  # source://console_table//lib/console_table.rb#88
  def print_header; end

  private

  # source://console_table//lib/console_table.rb#276
  def calc_column_widths; end

  # source://console_table//lib/console_table.rb#178
  def footer_lines; end

  # source://console_table//lib/console_table.rb#334
  def format(length, text, ellipsize = T.unsafe(nil), justify = T.unsafe(nil)); end

  # source://console_table//lib/console_table.rb#252
  def infer_justify_from_string(to_print, justify); end

  # source://console_table//lib/console_table.rb#264
  def normalize(string); end

  # source://console_table//lib/console_table.rb#189
  def print(options); end

  # source://console_table//lib/console_table.rb#129
  def print_headings; end

  # source://console_table//lib/console_table.rb#154
  def print_line(char = T.unsafe(nil), join_char = T.unsafe(nil), edge_join_only = T.unsafe(nil)); end

  # source://console_table//lib/console_table.rb#390
  def print_plain(to_print); end

  # source://console_table//lib/console_table.rb#174
  def should_print_footer; end

  # source://console_table//lib/console_table.rb#330
  def uncolorize(string); end
end
